### ISSUE TITLE
robbingkit consumption

### ISSUE THREAD

**Issue by RizzooTv** [Hailey-Ross/prp_graverobbing#1]
The robbingkit shouldn't disappear from the inventory after use, that doesn't make sense, maybe you can change that, or make an option in the config would be super nice :D

Best wishes

**Comment by Hailey-Ross** [comment]
Ah I like the idea, will implement it <3

**Comment by Hailey-Ross** [comment]
Will be working on a system in the coming days that there is a low chance the kit is destroyed otherwise they get to keep the kit.

**Comment by Hailey-Ross** [comment]
All changes pushed through, please update all files as there have been minor changes in all of them and major in the config.lua + server.lua
