### ISSUE TITLE
query sheriff

### ISSUE THREAD

**Issue by RizzooTv** [Hailey-Ross/prp_graverobbing#4]
Can you maybe add that you have the option that it only works if a sheriff is online? with one job query for several jobs

**Comment by Hailey-Ross** [comment]
Will be looking into implementing this <3

**Comment by Hailey-Ross** [comment]
Was very busy this weekend but will be working on making this a thing over the next week.

**Comment by Hailey-Ross** [comment]
Development on this resource has concluded, anyone is welcome to fork and add any changes they would like but for the time being I wont actively be working on RedM Development
